routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.master');
});

Auth::routes();
Route::group(['prefix' => 'dashboard','namespace'=>'admin',"middleware"=>'auth'],function(){



    Route::resource('services',"ServiceController");
    Route::resource('clients',"client_opinions_Controller");
    Route::get("/photoes/create","photoesController@create");
    Route::post("/photoes/store","photoesController@store")->name('photoes.store');
    Route::get('/photoes',"photoesController@index");

    Route::delete('/photoes/{id}',"photoesController@delete")->name("photoes.destroy");

});

Route::get('/home', 'website@show')->name('home');

app/Http/Controllers/Admin/client_opinions_Controller.php
<?php

namespace App\Http\Controllers\Admin;

use App\clients;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
class client_opinions_Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $clients=clients::all();
         return view('admin.client_opinions.index')->with(["clients"=>$clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.client_opinions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs=$request->all();
        // return ($inputs['permission']);

        $rules = [
            'name'=>'required|string|max:191',
            'opinion'=>'required|string',

        ];
        $this->validate($request,$rules);


        if($file=$request->file('image'))
        {
            $name="client".$file->getClientOriginalName();
       $file->move("images",$name);
            $inputs['image']=$name;

        }




       clients::create($inputs);


        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client=clients::find($id);
        return  view ("Admin.client_opinions.update",compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $inputs=$request->all();

//
//dd($request);
        $rules = [
            'name'=>'required|string|max:191',
            'opinion'=>'required|string',

        ];
        $this->validate($request,$rules);
          if( $file=$request->file('image'))
          {


            $name="client".$file->getClientOriginalName();
            $file->move("images",$name);
            $inputs['image']=$name;

          }
  clients::find($id)->update($inputs);

          return back();



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/client_opinions/create.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">



                <h4 class="header-title m-t-0 m-b-30">Input Types</h4>

    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
            @if (session()->has('success'))
                <div class="alert alert-success">
                        <h4>{{session()->get('success')}}</h4>
                </div>
            @endif

        <div class="col-lg-6">
            {!! Form::open(["route"=>'clients.store' ,'method'=>'post',"files"=>true]) !!}



@include('admin.client_opinions.form')


                <div class="form-group">

                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </div>
                </div>

    {!! Form::close() !!}
        </div><!-- end col -->



    </div><!-- end row -->
    </div>
    </div><!-- end col -->
    </div>
    <!-- end row -->


@endsection

resources/views/admin/client_opinions/form.blade.php
<div class="form-group">
    <label class="col-md-2 control-label">الإسم</label>
    <div class="col-md-10">
        {!! Form::text('name',null,["class"=>'form-control']) !!}

    </div>
</div>




<div class="form-group">
    <label class="col-md-2 control-label">الراي</label>
    <div class="col-md-10">
        {!! Form::text("opinion",null,["class"=>"form-control"]) !!}
       </div>
</div>
<div class="form-group">
    <label class="col-md-2 control-label">الصوره</label>
    <div class="col-md-10">
        {!! Form::file("image",null,["class"=>"form-control"]) !!}
    </div>
</div>

resources/views/admin/client_opinions/index.blade.php
@extends('admin.layout.master')

@section('styles')
@endsection


@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <div class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
                        <i class="zmdi zmdi-more-vert"></i>
                    </a>
                   

                <table id="datatable-buttons" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>الإسم</th>
                        <th>الراي</th>
                        <th>الصورة</th>
                        <th> حذف</th>
                        <th>تعديل</th>


                    </tr>
                    </thead>

                    <tbody>
                    @forelse($clients as $client)
                    <tr>
                        <td>{{$client->name}}</td>
                        <td>{{$client->opinion}}</td>

                        <td>
                            <img src="/images/{{$client->image}}" style="width: 100px; height: 100px; border-radius: 50%;">
                        </td>
                        <td>

                            <a href="/dashboard/clients/{{$client->id}}/edit" class="btn btn-primary">تعديل</a>  </td>
                        <td>
                            <form action="{{ route('clients.destroy',$client->id) }}" method="POST">




                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>

                            {{-- @endif--}}
                        </td>
                    </tr>
                        


                        @empty
                        <tr>
                            <td></td>
                            <td></td>
                            <td> </td>
                            <td> </td>
                            <td></td>
                        </tr>
                    @endforelse

                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->

@endsection



@section('scripts')
@endsection

resources/views/admin/client_opinions/update.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">



                <h4 class="header-title m-t-0 m-b-30">Input Types</h4>

                <div class="row">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (session()->has('success'))
                        <div class="alert alert-success">
                            <h4>{{session()->get('success')}}</h4>
                        </div>
                    @endif
                        <div class="col-lg-6">

{{$client->name}}



                            {!! Form::model($client,['route'=>['clients.update',$client->id],"files"=>true,"method"=>"PATCH"]) !!}

                       @include("admin.client_opinions.form")
                            
                            <div class="form-group">

                                <div class="col-md-10">
                                    <button type="submit" class="btn btn-primary">تعديل</button>
                                </div>
                            </div>

                   {!! Form::close() !!}
                    </div><!-- end col -->



                </div><!-- end row -->

                            {!! Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->


@endsection